### ISSUE TITLE
MAFA dataset has not been accessible!

### ISSUE THREAD

**Issue by hosseinzadeh88** [NVIDIA-AI-IOT/face-mask-detection#10]
The link to the MAFA dataset was generating a 404 error for the past month or so! Now that the link is not giving you a 404 error it takes you to a Chinese website (https://pan.baidu.com/s/1qiflOq65yMNNTXyt8020GA).
When I log in with the 4fz6 pass-code it asks me to download and install the latest version of the Network Disk Client. Which is also in Chinese.
Could you, after the 3rd attempt, finally fix this please?!

**Comment by ak-nv** [comment]
I could download at my end. In [Issue 3](https://github.com/NVIDIA-AI-IOT/face-mask-detection/issues/3) we have Google Drive link. Let me know if that works.
