### ISSUE TITLE
Data set are stored in the Mandarin site and can not access

### ISSUE THREAD

**Issue by robelsharma** [NVIDIA-AI-IOT/face-mask-detection#15]
Data are stored on Baidu and all chinese/mandarin. 
Can not access.
Please post them in google drive or someother sites where can be easily accessed.

**Comment by robelsharma** [comment]
Found some good soul put a link of google drive on the closed issue. Repo should be managed well as it is done by NVIDIA as a company. Rather than posting/uploading things on the risky and unuseful site put them on the google drive.

**Comment by ak-nv** [comment]
Just updated the readme with Google drive link. Thanks for suggesting.
