### ISSUE TITLE
Low FPS in Jetson Nano (11 FPS)

### ISSUE THREAD

**Issue by lakshaychhabra** [NVIDIA-AI-IOT/face-mask-detection#17]
Hi, 
I trained the model and pruned it 30% (instead of 12% as mentioned in Readme) in hope of getting more FPS. But unfortunately getting only ~11FPS (FP16). Is there any chance of increasing FPS by pruning it to 80%?

Also, I am unable to detect mask as Bounding boxes are not displayed in Deepstream.

**Comment by marekjg** [comment]
Regarding bounding boxes in deepstream, you might want to try hints in #11 but it didn't help in my case

**Comment by lakshaychhabra** [comment]
Well, I changed the input size and FPS increased to 25.

**Comment by craston** [comment]
@lakshaychhabra Did you manage to detect the mask as bbox in Deepstream. Currently I do not see any  bbox in Deepstream

**Comment by lakshaychhabra** [comment]
@craston yes I managed to detect the mask as bbox, 
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
tlt-model-key="my-key"
tlt-encoded-model=final_model.etlt
labelfile-path=labels_masknet.txt
# GPU Engine File
model-engine-file=final_model.etlt_b6_gpu0_fp16.engine
input-dims=3;300;300;0
uff-input-blob-name=input_1
force-implicit-batch-dim=1
batch-size=1
network-mode=2
process-mode=1
num-detected-classes=2
interval=4
gie-unique-id=2
output-blob-names=output_bbox/BiasAdd;output_cov/Sigmoid
cluster-mode=1

[class-attrs-all]
pre-cluster-threshold=0.2
eps=0.3
minBoxes=1
#can be tweaked
group-threshold=1

[application]
enable-perf-measurement=1
perf-measurement-interval-sec=1

**This was my updated config file, try changing [class-attrs-all] in your config file**

**Comment by craston** [comment]
Thanks I got it to work!
