### ISSUE TITLE
How to infer from jetson nano with a camera using deep stream

### ISSUE THREAD

**Issue by KOOKDONGHUN** [NVIDIA-AI-IOT/face-mask-detection#20]
I followed the tlt flow provided by GitHub.

Docker pool nvcr.io/nvidia/tlt-streamanalytics:v2.0_py3

I was trained in the docker container above.

I trained on Tesla V100 SXM2 32G multi-GPU environment.

Of the cells provided by face-mask-detection.ipynb, all cells except tlt-evaluate and tlt-infer ran without error.

I would like to use the face mask detection model provided by GitHub on jetson nano for real-time inference via webcam.

What docker should i use

I ran tlt-convert but it still failed to create the .engine file.

How do I create .engine file?

**Comment by craston** [comment]
@KOOKDONGHUN Did you solve this? If yes, could you please elaborate on the steps.
