### ISSUE TITLE
Dataset links not working

### ISSUE THREAD

**Issue by Ziegan** [NVIDIA-AI-IOT/face-mask-detection#3]
Hi,
I cannot open the links you provided for dataset **_Faces with Mask_**

The kaggle shows 404 error & The link From MAFA shows 403 Forbidden
Can you provide the working links .., and how much images did you had for mask and without mask upon training?

**Comment by ak-nv** [comment]
For MaFA dataset; some researchers have put it on Google Drive: https://drive.google.com/drive/folders/1nbtM1n0--iZ3VVbNGhocxbnBGhMau_OG . Please refer here.

**Comment by Ziegan** [comment]
Thanks for your help!

**Comment by lakshaychhabra** [comment]
Hi, Thanks for the drive link as accessing Baidu is very difficult. Please update the readme file so others don't suffer much.
