### ISSUE TITLE
error:Message type 'ClassWiseBboxHandlerConfig' has no field named 'confidence_threshold'

### ISSUE THREAD

**Issue by deepxiaobai** [NVIDIA-AI-IOT/face-mask-detection#32]
The error occurred when I used the retrained model to test some images.

**Comment by relaxtheo** [comment]
I just delete them, don't know the reason. I guess current code is for TLT 2.0

**Comment by deepxiaobai** [comment]
@relaxtheo Yes，just remove them makes the code to run. However, the results will have some noise. so are there any other properties to replace them?

**Comment by deepxiaobai** [comment]
Here, my TLT version is 3.0.0 and tutorial document has not been modified. I solve it with the latest configuration file.
