### ISSUE TITLE
Performance and edge deployment

### ISSUE THREAD

**Issue by hectormdom** [NVIDIA-AI-IOT/face-mask-detection#8]
Hi, thanks again for all your help, I've been trying really hard to make this work but I have a couple issues, when I run the code in the workstation using a webcam, I get fantastic FPS, however even under great lighting conditions it behaves in a funny way, It sort of waits (I don't know if it's like buffering) for a minute, then it shows a ton of inferences all at the same time, like "no mask" with a ton of red frames, then no inference at all, then again a lot of inferences all at the same time.

Also I tried deploying it to the  jetson nano (because I thought this behaviour could somehow using the model in a deployment), I got all the way up to getting the trt file and the fp16 engine, but after checking a lot of documentation, and all the versions and conflicts I ended up so very confused, most of the posts I find seem outdated, and not compatible with for example, tensorflow 2.x, 

I would like to deploy the trained model using the jetson.inference module in python, in order to integrate it with the jetson GPIO, but I just can't find a concrete example, is there any chance you could redirect me to what I have to read/study in order to do this? Something like this: https://github.com/dusty-nv/jetson-inference/blob/master/docs/detectnet-example-2.md ? Cheers!

**Comment by ak-nv** [comment]
Currently, TLT model can be deployed with DeepStream and not supported for `jetson-inference` 
Once you get etlt model; you can use DeepStream as suggested in [Readme](https://github.com/NVIDIA-AI-IOT/face-mask-detection#steps-to-perform-face-detection-with-mask): Perform inference using DeepStream SDK on Jetson


Please let me know if you have questions for deploying it using DS.
